server:
  port: 8183
  servlet:
    context-path: /provider
logging:
  level:
    com: debug


rpc:
  provider-enable: true
  server-address: localhost:7001
  register: zk
  register-address: 192.168.110.133:2181

